import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div>Admin layout</div>
      {children}
    </div>
  );
}
